"""Monotone descriptor -> parameter tables, generated by synthesis.

Two of the four axes cannot be inverted in closed form: the relationship
between "how much bright mass is in the histogram" and `add_glare`'s fill
value, and between 8x8 blockiness and JPEG quality, both depend on image
content and on the random ellipse `add_glare` draws. So they are measured
instead: sweep the forward parameter over a fixed sample, record the
descriptor, and store the table.

The table is checked in as JSON with `calibrate.py` beside it. That makes
the numbers reproducible, costs nothing at runtime, and -- because the
sweep drives `degrade.py` itself -- keeps the units native to `degrade.py`
by construction rather than by a conversion someone has to maintain.
"""

import json
import os
from dataclasses import dataclass

DEFAULT_CURVES_PATH = os.path.join(os.path.dirname(__file__), "curves.json")


@dataclass(frozen=True)
class Curve:
    """A monotone-increasing descriptor as a function of one parameter.

    `points` is [(parameter_value, descriptor), ...] sorted ascending by
    parameter. `parameter` is "strength" for the axes that invert to a
    continuous strength, and "kernel" for blur, whose forward parameter is
    a quantised odd kernel size.
    """

    name: str
    parameter: str
    points: list[tuple[float, float]]

    def __post_init__(self):
        if len(self.points) < 2:
            raise ValueError(f"curve {self.name!r} needs at least two points")
        values = [p for p, _ in self.points]
        if values != sorted(values):
            raise ValueError(f"curve {self.name!r} parameters are not sorted ascending")
        descriptors = self.descriptors()
        if descriptors != sorted(descriptors):
            raise ValueError(
                f"curve {self.name!r} descriptor is not monotone increasing: "
                f"{descriptors} -- two parameters map to one reading, so it "
                "cannot be inverted. Re-run the sweep with more samples."
            )

    def descriptors(self) -> list[float]:
        return [d for _, d in self.points]


@dataclass(frozen=True)
class CurveBundle:
    generated_by: str
    sample_images: int
    seeds: int
    curves: dict[str, Curve]


def interpolate(curve: Curve, descriptor: float) -> tuple[float, bool]:
    """Invert `curve` at `descriptor`. Returns (parameter_value, saturated).

    Below the first calibrated point the answer clamps to that point and
    is NOT saturated: "less degraded than anything we calibrated" is a
    real reading. Above the last point it clamps and IS saturated,
    because that is where the forward transform's own `min(strength, 1.0)`
    has gone flat and the true value is unrecoverable. Extrapolating past
    the end would invent a number the data cannot support.
    """
    points = curve.points
    if descriptor <= points[0][1]:
        return (float(points[0][0]), False)
    if descriptor >= points[-1][1]:
        return (float(points[-1][0]), True)
    for (v0, d0), (v1, d1) in zip(points, points[1:]):
        if d0 <= descriptor <= d1:
            if d1 == d0:
                return (float(v0), False)
            span = (descriptor - d0) / (d1 - d0)
            return (float(v0 + span * (v1 - v0)), False)
    raise AssertionError(f"descriptor {descriptor} fell through curve {curve.name!r}")


def nearest(curve: Curve, descriptor: float) -> float:
    """Parameter value of the closest calibrated point.

    Used where the forward parameter is quantised and interpolating
    between calibrated points would claim a precision that does not
    exist -- `motion_blur`'s kernel size is `int(3 + 12 * strength) | 1`,
    so only odd sizes are reachable and there is no such thing as a
    kernel of 4.
    """
    return float(min(curve.points, key=lambda p: abs(p[1] - descriptor))[0])


def save_bundle(bundle: CurveBundle, path: str) -> None:
    payload = {
        "generated_by": bundle.generated_by,
        "sample_images": bundle.sample_images,
        "seeds": bundle.seeds,
        "curves": {
            name: {"parameter": c.parameter, "points": [list(p) for p in c.points]}
            for name, c in sorted(bundle.curves.items())
        },
    }
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp = f"{path}.part"
    with open(tmp, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")
    os.replace(tmp, path)


def load_bundle(path: str = DEFAULT_CURVES_PATH) -> CurveBundle:
    """Load the calibration bundle. A missing file is fatal, never empty.

    Defaulting to an empty bundle would make every estimator report the
    image as undegraded -- a plausible-looking wrong answer, which is
    worse than a crash.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"no calibration curves at {path}. Generate them with "
            "`uv run python -m hitcheck_trainer.augment.calibrate` "
            "(see docs/runbooks/2026-08-31-m2-axis-measurement.md)."
        )
    with open(path) as fh:
        payload = json.load(fh)
    return CurveBundle(
        generated_by=payload["generated_by"],
        sample_images=payload["sample_images"],
        seeds=payload["seeds"],
        curves={
            name: Curve(
                name=name,
                parameter=body["parameter"],
                points=[(float(v), float(d)) for v, d in body["points"]],
            )
            for name, body in payload["curves"].items()
        },
    )
