"""Monotone descriptor -> parameter tables, generated by synthesis.

Two of the four axes cannot be inverted in closed form: the relationship
between "how much bright mass is in the histogram" and `add_glare`'s fill
value, and between 8x8 blockiness and JPEG quality, both depend on image
content and on the random ellipse `add_glare` draws. So they are measured
instead: sweep the forward parameter over a fixed sample, record the
descriptor, and store the table.

The table is checked in as JSON with `calibrate.py` beside it. That makes
the numbers reproducible, costs nothing at runtime, and -- because the
sweep drives `degrade.py` itself -- keeps the units native to `degrade.py`
by construction rather than by a conversion someone has to maintain.
"""

import itertools
import json
import math
import os
from dataclasses import dataclass

DEFAULT_CURVES_PATH = os.path.join(os.path.dirname(__file__), "curves.json")


@dataclass(frozen=True)
class Curve:
    """A monotone-increasing descriptor as a function of one parameter.

    `points` is [(parameter_value, descriptor), ...] sorted ascending by
    parameter. `parameter` is "strength" for the axes that invert to a
    continuous strength, and "kernel" for blur, whose forward parameter is
    a quantised odd kernel size.
    """

    name: str
    parameter: str
    points: list[tuple[float, float]]

    def __post_init__(self):
        if len(self.points) < 2:
            raise ValueError(f"curve {self.name!r} needs at least two points")
        values = [p for p, _ in self.points]
        if any(b <= a for a, b in itertools.pairwise(values)):
            raise ValueError(
                f"curve {self.name!r} parameters are not strictly ascending: {values}"
            )
        descriptors = self.descriptors()
        # STRICTLY increasing, not merely non-decreasing. A tie means two
        # parameters produce one descriptor reading -- exactly the
        # "cannot be inverted" case this check exists for -- and
        # `sorted()` comparison would wave it through, leaving
        # `interpolate` to silently pick one side of the tie. On a real
        # sweep a tie means the two settings are indistinguishable, which
        # has to fail loudly rather than resolve to a coin flip.
        if any(b <= a for a, b in itertools.pairwise(descriptors)):
            raise ValueError(
                f"curve {self.name!r} descriptor is not strictly increasing: "
                f"{descriptors} -- two parameters map to one reading, so it "
                "cannot be inverted. Re-run the sweep with more samples."
            )

    def descriptors(self) -> list[float]:
        return [d for _, d in self.points]


@dataclass(frozen=True)
class CurveBundle:
    generated_by: str
    sample_images: int
    seeds: int
    curves: dict[str, Curve]


def _reject_non_finite(curve: Curve, descriptor: float) -> None:
    """A non-finite descriptor is a bug upstream, not a reading. Fail loudly.

    All three inverters share this because their silent failures differ
    and none of them is safe: `min(..., key=abs(p[1] - nan))` compares
    False every time and returns the FIRST point (kernel 1, "perfectly
    sharp"), while `interpolate` falls through to an AssertionError. A
    descriptor that cannot be measured must arrive here as `None` and be
    turned into an unavailable `AxisEstimate` by the caller, never as NaN.
    """
    if not math.isfinite(descriptor):
        raise ValueError(
            f"descriptor {descriptor} is not finite; curve {curve.name!r} cannot "
            "invert it. An unmeasurable descriptor must be reported as None "
            "(unavailable), not passed through as NaN."
        )


def interpolate(curve: Curve, descriptor: float) -> tuple[float, bool]:
    """Invert `curve` at `descriptor`. Returns (parameter_value, saturated).

    Below the first calibrated point the answer clamps to that point and
    is NOT saturated: "less degraded than anything we calibrated" is a
    real reading. Above the last point it clamps and IS saturated,
    because that is where the forward transform's own `min(strength, 1.0)`
    has gone flat and the true value is unrecoverable. Extrapolating past
    the end would invent a number the data cannot support.
    """
    _reject_non_finite(curve, descriptor)
    points = curve.points
    if descriptor <= points[0][1]:
        return (float(points[0][0]), False)
    if descriptor >= points[-1][1]:
        return (float(points[-1][0]), True)
    for (v0, d0), (v1, d1) in itertools.pairwise(points):
        if d0 <= descriptor <= d1:
            # d1 > d0 is guaranteed by Curve.__post_init__'s strict check,
            # so this division cannot be by zero.
            span = (descriptor - d0) / (d1 - d0)
            return (float(v0 + span * (v1 - v0)), False)
    raise AssertionError(f"descriptor {descriptor} fell through curve {curve.name!r}")


def extrapolate(curve: Curve, descriptor: float) -> float:
    """Invert `curve`, extending the last segment instead of saturating.

    For the axes whose forward transform has NO `min(strength, 1.0)`
    clamp. `perspective_warp`'s `shift = 0.12 * strength` is unbounded and
    strength 2.0 is both representable and recoverable, so reporting
    ">= 1.0" above the last calibrated point would be a false claim about
    the forward model -- and, because `measure.axis_medians` EXCLUDES
    saturated estimates, it would silently drop exactly the most-warped
    cards out of the corpus median.

    Extrapolation is only defensible where the curve is straight, and the
    perspective curve is straight by construction: `warped_corners` scales
    a fixed uniform draw by `shift = 0.12 * strength`, so its expected
    corner deviation is proportional to strength. Measured on the shipped
    curve, descriptor/strength runs 0.06412 / 0.06402 / 0.06392 / 0.06382
    / 0.06373 across the five non-zero points -- a 0.6% droop end to end,
    from the de-rotation in `quad_corner_deviation` absorbing slightly
    more of a larger jitter. The slope of the last segment is the slope
    everywhere to well inside this axis's per-image noise.

    Below the first point this clamps exactly like `interpolate` -- "less
    degraded than anything calibrated" is a real reading with a floor at
    the curve's first parameter, not an invitation to report a negative
    strength.
    """
    _reject_non_finite(curve, descriptor)
    points = curve.points
    if descriptor <= points[0][1]:
        return float(points[0][0])
    if descriptor < points[-1][1]:
        return interpolate(curve, descriptor)[0]
    (v0, d0), (v1, d1) = points[-2], points[-1]
    # d1 > d0 by Curve.__post_init__'s strict monotonicity check.
    return float(v1 + (descriptor - d1) * (v1 - v0) / (d1 - d0))


def nearest(curve: Curve, descriptor: float) -> float:
    """Parameter value of the closest calibrated point.

    Used where the forward parameter is quantised and interpolating
    between calibrated points would claim a precision that does not
    exist -- `motion_blur`'s kernel size is `int(3 + 12 * strength) | 1`,
    so only odd sizes are reachable and there is no such thing as a
    kernel of 4.
    """
    _reject_non_finite(curve, descriptor)
    return float(min(curve.points, key=lambda p: abs(p[1] - descriptor))[0])


def save_bundle(bundle: CurveBundle, path: str) -> None:
    payload = {
        "generated_by": bundle.generated_by,
        "sample_images": bundle.sample_images,
        "seeds": bundle.seeds,
        "curves": {
            name: {"parameter": c.parameter, "points": [list(p) for p in c.points]}
            for name, c in sorted(bundle.curves.items())
        },
    }
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp = f"{path}.part"
    with open(tmp, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")
    os.replace(tmp, path)


def load_bundle(path: str = DEFAULT_CURVES_PATH) -> CurveBundle:
    """Load the calibration bundle. A missing file is fatal, never empty.

    Defaulting to an empty bundle would make every estimator report the
    image as undegraded -- a plausible-looking wrong answer, which is
    worse than a crash.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"no calibration curves at {path}. Generate them with "
            "`uv run python -m hitcheck_trainer.augment.calibrate` "
            "(see docs/runbooks/2026-08-31-m2-axis-measurement.md)."
        )
    with open(path) as fh:
        payload = json.load(fh)
    return CurveBundle(
        generated_by=payload["generated_by"],
        sample_images=payload["sample_images"],
        seeds=payload["seeds"],
        curves={
            name: Curve(
                name=name,
                parameter=body["parameter"],
                points=[(float(v), float(d)) for v, d in body["points"]],
            )
            for name, body in payload["curves"].items()
        },
    )
