"""The inverse of `degrade.py`: where does this image sit on each axis?

Output is four INDEPENDENT strength-equivalents, never one scalar.
`degrade.degrade` drives four transforms off a single `strength`, which
makes that scalar a diagonal through a four-dimensional space rather than
an axis; a real frame sits at some arbitrary point in that space and may
never lie near the diagonal. Collapsing these four numbers back into one
would re-create exactly the defect this module exists to fix.

STATED LIMIT, and it belongs in every write-up that quotes these numbers:
these estimators recover `degrade.py`'s PARAMETERS, not physical ground
truth. "blur-strength 0.35" means "as blurry as `motion_blur` at 0.35" --
it is not a claim about the real point-spread function. That is exactly
the number needed to read the M2 curve, and it must be labelled that way
so it is not later mistaken for a physical measurement.
"""

import argparse
import functools
import io
import os
import statistics
import sys
from dataclasses import dataclass

from PIL import Image

from ..corpus.crops import apply_quad, load_crops, load_skips
from ..corpus.manifest import load_manifest
from .curves import Curve, CurveBundle, interpolate, load_bundle, nearest
from .descriptors import blockiness, bright_tail_mass, quad_corner_deviation, reblur_ratio

# degrade.jpeg_artifacts: quality = int(max(8, 60 - 45 * min(strength, 1.0)))
# so strength 0 -> 60 and strength 1 -> 15. The max(8, ...) floor is
# unreachable, which makes 15 the saturation marker and 60 the "no JPEG
# axis was applied" marker.
JPEG_QUALITY_AT_ZERO = 60
JPEG_QUALITY_AT_ONE = 15


@dataclass(frozen=True)
class AxisEstimate:
    """One axis's strength-equivalent.

    `strength is None` means the axis could not be measured on this input
    at all (no quantization table, no recorded quad) -- distinct from a
    measured 0.0. `saturated` means the forward transform clamped and the
    true value is at least this, unrecoverably: `add_glare` and
    `jpeg_artifacts` both use `min(strength, 1.0)` and are flat above it.
    """

    strength: float | None
    saturated: bool = False

    def __str__(self) -> str:
        if self.strength is None:
            return "unavailable"
        return f"{'>= ' if self.saturated else ''}{self.strength:.2f}"


@dataclass(frozen=True)
class DegradationProfile:
    """Four axes. Deliberately no aggregate -- see the module docstring."""

    jpeg: AxisEstimate
    blur: AxisEstimate
    perspective: AxisEstimate
    glare: AxisEstimate

    def summary(self) -> str:
        return (
            f"jpeg={self.jpeg} blur={self.blur} "
            f"perspective={self.perspective} glare={self.glare}"
        )


@functools.lru_cache(maxsize=1)
def _reference_tables() -> dict[int, tuple[int, ...]]:
    """Luma quantization table PIL emits at each quality, 1-100.

    Generated by encoding rather than hard-coded from IJG Annex K on
    purpose. Hard-coding requires knowing whether PIL reports coefficients
    in zigzag or natural order -- an undocumented detail that has moved
    across Pillow versions, and one whose failure mode is silent: a
    wrong-order comparison still returns a quality, just the wrong one.
    Encoding through PIL matches the exact encoder `jpeg_artifacts` uses.
    """
    probe = Image.new("RGB", (16, 16), (128, 128, 128))
    tables = {}
    for quality in range(1, 101):
        buffer = io.BytesIO()
        probe.save(buffer, format="JPEG", quality=quality)
        buffer.seek(0)
        with Image.open(buffer) as encoded:
            tables[quality] = tuple(encoded.quantization[0])
    return tables


def jpeg_quality(image: Image.Image) -> int | None:
    """The libjpeg quality this image was last encoded at, or None.

    None means there is no quantization table to read -- a PNG, or a
    decoded H.264 stream frame. Those go through the blockiness fallback
    instead; guessing here would be worse than declining.

    Ties resolve to the LOWEST matching quality. Adjacent qualities share
    a table at the top of the range, where the difference is below the
    JPEG axis's floor of 60 anyway, and resolving downward keeps the
    estimator from understating degradation.
    """
    tables = getattr(image, "quantization", None)
    if not tables or 0 not in tables:
        return None
    observed = tuple(tables[0])
    best_quality, best_distance = None, None
    for quality, reference in _reference_tables().items():
        if len(reference) != len(observed):
            continue
        distance = sum(abs(a - b) for a, b in zip(observed, reference, strict=True))
        if best_distance is None or distance < best_distance:
            best_quality, best_distance = quality, distance
    return best_quality


def estimate_jpeg(image: Image.Image) -> AxisEstimate:
    """JPEG strength-equivalent read exactly off the file header.

    `image` must be one PIL opened from JPEG bytes and NOT converted --
    `.convert()` drops `quantization`, so `jpeg_artifacts`' own return
    value cannot be passed here. Real inputs are files on disk, which do
    carry the table.

    `degrade.py` truncates quality with `int()`, so the recovered strength
    is biased high by up to 1/45 = 0.023. Nothing tighter is available
    from the header, and it is well inside the resolution this axis is
    read at.
    """
    quality = jpeg_quality(image)
    if quality is None:
        return AxisEstimate(None)
    if quality <= JPEG_QUALITY_AT_ONE:
        return AxisEstimate(1.0, saturated=True)
    if quality >= JPEG_QUALITY_AT_ZERO:
        return AxisEstimate(0.0)
    return AxisEstimate((JPEG_QUALITY_AT_ZERO - quality) / 45.0)


def strength_for_kernel(kernel: int) -> float:
    """Midpoint of the strength interval that produces this blur kernel.

    `motion_blur` uses `k = int(3 + 12 * strength) | 1`, so the forward
    map is many-to-one: `int(3 + 12s)` in {k-1, k} both give kernel k,
    which is `s` in [(k-4)/12, (k-2)/12). The inverse is therefore an
    INTERVAL, not a point, and reporting its midpoint is the most a
    kernel size can honestly say. Worst-case error is half the widest
    interval, 1/12.

    Kernel 1 is the sentinel for "no blur applied at all" -- `motion_blur`
    returns the image untouched at strength <= 0 rather than convolving
    with a 3-tap kernel, so that case is genuinely 0.0 and not 1/24.
    """
    if kernel == 1:
        return 0.0
    if kernel < 3 or kernel % 2 == 0:
        raise ValueError(f"kernel {kernel} is not an odd size >= 3 (or the 1 sentinel)")
    low = max(0.0, (kernel - 4) / 12.0)
    high = (kernel - 2) / 12.0
    return (low + high) / 2.0


def estimate_blur(image: Image.Image, curve: Curve) -> AxisEstimate:
    """Motion-blur strength-equivalent, via the re-blur ratio.

    CORPUS-LEVEL ONLY, like perspective and glare. `motion_blur` picks a
    random angle per seed and `reblur_ratio` responds to angle as well as
    to kernel size, because real content is anisotropic. Measured on
    catalog scans, the within-image spread across angles at a fixed
    kernel (0.014-0.040) is three to nine times the gap between adjacent
    kernels' calibration points (0.004-0.011) -- so a single image cannot
    resolve its own kernel and a per-image reading is noise. Average over
    a corpus.

    COMPRESSES ABOVE ROUGHLY 0.4. The curve's adjacent gaps shrink from
    0.010 to 0.004 across the kernel range as the ratio saturates, so
    heavy blur is systematically UNDER-reported: measured mean recovery
    on catalog scans is -0.11 at strength 0.6 and -0.39 at 0.9. The bias
    is one-directional by design of the descriptor, and under-reporting
    is the safe direction here -- it makes a corpus look sharper than it
    is, biasing the M2 extrapolation toward "training required" rather
    than toward skipping training we needed.

    Never saturates the way glare and JPEG do in the `AxisEstimate`
    sense: `motion_blur` has no `min(strength, 1.0)` clamp, and kernel 15
    is reachable from strengths up to 13/12. `nearest` rather than
    `interpolate` because the forward parameter is quantised to odd
    kernel sizes and interpolating between calibrated points would claim
    a precision that does not exist.
    """
    return AxisEstimate(strength_for_kernel(round(nearest(curve, reblur_ratio(image)))))


def estimate_perspective(quad: list[list[float]], curve: Curve) -> AxisEstimate:
    """Perspective strength-equivalent from a recorded card quadrilateral.

    ONE SAMPLE, NOT THE PARAMETER. `perspective_warp` draws its corner
    jitter from `rng.uniform(-shift, shift, (4, 2))`, so this number is a
    single realisation of that draw and is noisy per image; it is only
    meaningful averaged over a corpus. Every caller that prints it must
    say so.

    The descriptor is closed-form (max normalised corner offset from the
    best-fit rectangle) but its relationship to `shift` is not: the
    best-fit rectangle is built from corner means, so each deviation is a
    half-difference of two uniforms and the max over four of those sits
    systematically below `shift`. Rather than derive that constant, the
    curve measures it -- which also means the estimator stays correct if
    `perspective_warp`'s jitter distribution ever changes.
    """
    strength, saturated = interpolate(curve, quad_corner_deviation(quad))
    return AxisEstimate(strength, saturated=saturated)


def estimate_glare(image: Image.Image, curve: Curve) -> AxisEstimate:
    """Specular-glare strength-equivalent from the bright tail of the histogram.

    Saturates: `add_glare` fills with `int(190 * min(strength, 1.0))`, so
    strength 1.0 and strength 2.5 produce identical pixels and anything at
    the top of the curve reports ">= 1.0" rather than a point value.

    Usable per image, unlike `estimate_blur` and `estimate_perspective`.
    The ellipse's centre and radii are random draws, but measured across
    eight catalog scans every seed produces signal at every strength and
    the mean-vs-median gap stays near 4% -- small against the calibration
    gap between adjacent strengths.

    The real caveat is the content term: the descriptor counts pixels
    above `GLARE_THRESHOLD`, so a card shot on a white desk starts with
    tail mass a card on black does not, and a source whose luma tops out
    below the threshold reads baseline no matter how much glare it
    carries. Compare readings within a source, not across sources.
    """
    strength, saturated = interpolate(curve, bright_tail_mass(image))
    return AxisEstimate(strength, saturated=saturated)


def estimate_jpeg_blockiness(image: Image.Image, curve: Curve) -> AxisEstimate:
    """JPEG strength-equivalent for inputs with no quantization table.

    Stream frames arrive as decoded H.264: the compression is real but the
    header is gone, so it has to be measured off the 8x8 grid instead.
    Strictly worse than `estimate_jpeg` -- calibrated rather than exact,
    and confounded by any blur applied after compression, which smooths
    the very block edges this counts. Use it only when the header is
    genuinely absent.

    Saturates for the same reason `estimate_jpeg` does: quality bottoms
    out at 15 and the descriptor goes flat past strength 1.0.
    """
    strength, saturated = interpolate(curve, blockiness(image))
    return AxisEstimate(strength, saturated=saturated)


def profile_image(
    image: Image.Image,
    quad: list[list[float]] | None = None,
    source: Image.Image | None = None,
    bundle: CurveBundle | None = None,
) -> DegradationProfile:
    """Locate one image on all four axes.

    The three inputs are not interchangeable, because the axes are not
    measured off the same pixels:

    `image` is the CARD CROP -- what actually gets embedded. Blur and
    glare come from here; a blurry desk behind a sharp card is not a
    degradation of the card.

    `source` is the ORIGINAL FILE as opened, header intact and NOT
    `.convert()`ed (which drops `quantization`). The JPEG axis is read
    exactly from it. Without it, or without a table in it, the axis falls
    back to blockiness measured on `image`.

    `quad` is the card's corners IN THE ORIGINAL PHOTOGRAPH'S
    COORDINATES. Unwarping the crop is exactly what destroys this
    evidence, so it cannot be recovered from `image`. Absent, the
    perspective axis reports unavailable rather than 0.0 -- "we did not
    measure it" and "we measured no warp" are different claims.
    """
    curves = (bundle or load_bundle()).curves

    jpeg = estimate_jpeg(source) if source is not None else AxisEstimate(None)
    if jpeg.strength is None:
        jpeg = estimate_jpeg_blockiness(image, curves["jpeg_blockiness"])

    perspective = (
        estimate_perspective(quad, curves["perspective"])
        if quad is not None
        else AxisEstimate(None)
    )

    return DegradationProfile(
        jpeg=jpeg,
        blur=estimate_blur(image, curves["blur"]),
        perspective=perspective,
        glare=estimate_glare(image, curves["glare"]),
    )


DEFAULT_CORPUS = "data/corpus"

AXES = ("jpeg", "blur", "perspective", "glare")


def axis_medians(profiles: list[DegradationProfile]) -> dict[str, tuple]:
    """Per axis: (median strength, how many were measured, how many saturated).

    Median rather than mean: glare and perspective are noisy per image
    with occasional large outliers, and a mean would chase them.

    Saturated estimates are COUNTED but excluded from the median. Their
    true value is unknown and at least the clamp; folding them in as 1.0
    would pull the median toward the clamp and make a corpus with a few
    blown highlights look uniformly glared. Unmeasured axes report None,
    which is a different claim from a measured 0.0.
    """
    summary = {}
    for axis in AXES:
        estimates = [getattr(p, axis) for p in profiles]
        usable = [e.strength for e in estimates if e.strength is not None and not e.saturated]
        saturated = sum(1 for e in estimates if e.strength is not None and e.saturated)
        median = statistics.median(usable) if usable else None
        summary[axis] = (median, len(usable), saturated)
    return summary


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="hitcheck-measure-corpus")
    parser.add_argument("--corpus", default=DEFAULT_CORPUS)
    parser.add_argument("--curves", default=None,
                        help="calibration bundle (default: the checked-in curves.json)")
    args = parser.parse_args(argv)

    manifest = load_manifest(os.path.join(args.corpus, "manifest.json"))
    crops = load_crops(os.path.join(args.corpus, "crops.json"))
    skips = load_skips(os.path.join(args.corpus, "skipped.json"))
    bundle = load_bundle(args.curves) if args.curves else load_bundle()

    profiles, failed = [], 0
    for entry in manifest.entries:
        quad = crops.get(entry.item_id)
        if quad is None or entry.item_id in skips:
            continue
        path = os.path.join(args.corpus, entry.image)
        if not (os.path.exists(path) and os.path.getsize(path) > 0):
            continue
        try:
            with Image.open(path) as source:
                # `source` keeps its quantization table for the JPEG axis;
                # the crop is what gets embedded, so blur and glare come
                # from there; the quad is in the ORIGINAL's coordinates,
                # which unwarping is exactly what destroys.
                crop = apply_quad(source, quad)
                profiles.append(profile_image(crop, quad=quad, source=source, bundle=bundle))
        except (OSError, ValueError):
            failed += 1

    print(f"corpus: {len(manifest.entries)} entries, {len(crops)} cropped, "
          f"{len(skips)} skipped, {len(profiles)} profiled, {failed} unreadable")
    if not profiles:
        print("No cropped corpus entries. Run the corpus build, then the crop tool "
              "(docs/runbooks/2026-08-31-m2-corpus.md).")
        return 1

    print()
    print("Median degradation-equivalent per axis:")
    for axis, (median, measured, saturated) in axis_medians(profiles).items():
        value = "unavailable" if median is None else f"{median:.3f}"
        note = f" ({saturated} saturated, excluded)" if saturated else ""
        print(f"  {axis:12s} {value:>12s}  n={measured}{note}")

    print()
    print("These are degrade.py's own parameters, not physical measurements: "
          "'blur 0.35' means 'as blurry as motion_blur at 0.35', and is not a "
          "physical measurement of the lens or the codec.")
    print("Perspective is a per-image sample of a uniform draw "
          "(degrade.py:71), so only the corpus median is meaningful; individual "
          "values are noisy. Blur is per-image noisy too -- reblur_ratio responds "
          "to the blur ANGLE as well as its size -- and it under-reports blur above "
          "roughly 0.4 as the descriptor saturates.")
    print("Measured on seller photographs, which are well-lit, static and "
          "high-resolution. A stream frame sits further along every axis.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
