"""The inverse of `degrade.py`: where does this image sit on each axis?

Output is four INDEPENDENT strength-equivalents, never one scalar.
`degrade.degrade` drives four transforms off a single `strength`, which
makes that scalar a diagonal through a four-dimensional space rather than
an axis; a real frame sits at some arbitrary point in that space and may
never lie near the diagonal. Collapsing these four numbers back into one
would re-create exactly the defect this module exists to fix.

STATED LIMIT, and it belongs in every write-up that quotes these numbers:
these estimators recover `degrade.py`'s PARAMETERS, not physical ground
truth. "blur-strength 0.35" means "as blurry as `motion_blur` at 0.35" --
it is not a claim about the real point-spread function. That is exactly
the number needed to read the M2 curve, and it must be labelled that way
so it is not later mistaken for a physical measurement.
"""

import functools
import io
from dataclasses import dataclass

from PIL import Image

# degrade.jpeg_artifacts: quality = int(max(8, 60 - 45 * min(strength, 1.0)))
# so strength 0 -> 60 and strength 1 -> 15. The max(8, ...) floor is
# unreachable, which makes 15 the saturation marker and 60 the "no JPEG
# axis was applied" marker.
JPEG_QUALITY_AT_ZERO = 60
JPEG_QUALITY_AT_ONE = 15


@dataclass(frozen=True)
class AxisEstimate:
    """One axis's strength-equivalent.

    `strength is None` means the axis could not be measured on this input
    at all (no quantization table, no recorded quad) -- distinct from a
    measured 0.0. `saturated` means the forward transform clamped and the
    true value is at least this, unrecoverably: `add_glare` and
    `jpeg_artifacts` both use `min(strength, 1.0)` and are flat above it.
    """

    strength: float | None
    saturated: bool = False

    def __str__(self) -> str:
        if self.strength is None:
            return "unavailable"
        return f"{'>= ' if self.saturated else ''}{self.strength:.2f}"


@dataclass(frozen=True)
class DegradationProfile:
    """Four axes. Deliberately no aggregate -- see the module docstring."""

    jpeg: AxisEstimate
    blur: AxisEstimate
    perspective: AxisEstimate
    glare: AxisEstimate

    def summary(self) -> str:
        return (
            f"jpeg={self.jpeg} blur={self.blur} "
            f"perspective={self.perspective} glare={self.glare}"
        )


@functools.lru_cache(maxsize=1)
def _reference_tables() -> dict[int, tuple[int, ...]]:
    """Luma quantization table PIL emits at each quality, 1-100.

    Generated by encoding rather than hard-coded from IJG Annex K on
    purpose. Hard-coding requires knowing whether PIL reports coefficients
    in zigzag or natural order -- an undocumented detail that has moved
    across Pillow versions, and one whose failure mode is silent: a
    wrong-order comparison still returns a quality, just the wrong one.
    Encoding through PIL matches the exact encoder `jpeg_artifacts` uses.
    """
    probe = Image.new("RGB", (16, 16), (128, 128, 128))
    tables = {}
    for quality in range(1, 101):
        buffer = io.BytesIO()
        probe.save(buffer, format="JPEG", quality=quality)
        buffer.seek(0)
        with Image.open(buffer) as encoded:
            tables[quality] = tuple(encoded.quantization[0])
    return tables


def jpeg_quality(image: Image.Image) -> int | None:
    """The libjpeg quality this image was last encoded at, or None.

    None means there is no quantization table to read -- a PNG, or a
    decoded H.264 stream frame. Those go through the blockiness fallback
    instead; guessing here would be worse than declining.

    Ties resolve to the LOWEST matching quality. Adjacent qualities share
    a table at the top of the range, where the difference is below the
    JPEG axis's floor of 60 anyway, and resolving downward keeps the
    estimator from understating degradation.
    """
    tables = getattr(image, "quantization", None)
    if not tables or 0 not in tables:
        return None
    observed = tuple(tables[0])
    best_quality, best_distance = None, None
    for quality, reference in _reference_tables().items():
        if len(reference) != len(observed):
            continue
        distance = sum(abs(a - b) for a, b in zip(observed, reference, strict=True))
        if best_distance is None or distance < best_distance:
            best_quality, best_distance = quality, distance
    return best_quality


def estimate_jpeg(image: Image.Image) -> AxisEstimate:
    """JPEG strength-equivalent read exactly off the file header.

    `image` must be one PIL opened from JPEG bytes and NOT converted --
    `.convert()` drops `quantization`, so `jpeg_artifacts`' own return
    value cannot be passed here. Real inputs are files on disk, which do
    carry the table.

    `degrade.py` truncates quality with `int()`, so the recovered strength
    is biased high by up to 1/45 = 0.023. Nothing tighter is available
    from the header, and it is well inside the resolution this axis is
    read at.
    """
    quality = jpeg_quality(image)
    if quality is None:
        return AxisEstimate(None)
    if quality <= JPEG_QUALITY_AT_ONE:
        return AxisEstimate(1.0, saturated=True)
    if quality >= JPEG_QUALITY_AT_ZERO:
        return AxisEstimate(0.0)
    return AxisEstimate((JPEG_QUALITY_AT_ZERO - quality) / 45.0)
